version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  gorcon:
    image: gorcon
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file:
      - app.env
    environment:
      dbhost: db
    links:
      - db
volumes:
  db:
    driver: local